version: 0.7.0-beta-*
os: Visual Studio 2015
install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: dnvm install 1.0.0-rc1-update1
  - cmd: dnu restore
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
test_script:
  - cmd: dnx -p .\tests\FlatMapper.Tests test
artifacts:
  - path: artifacts\bin\FlatMapper\$(configuration)\*.nupkg
deploy:
  provider: NuGet
  skip_symbols: true
  api_key:
    secure: c18PmLObjM4XzNKNj8/LzYty11gya98+IerJXipzMmL9wgmHS6cGAJWYpJkDxmU2
  artifact: /.*\.nupkg/